### ISSUE TITLE
Command as prompt (eg. starship)

### ISSUE THREAD

**Issue by theoparis** [Vaimer9/vsh#8]
Hi there. This looks like a really neat project! I would even consider using it instead of ZSH once piping and the scripting language features are fully implemented 😄 

Even though there isn't any of that yet, I don't see a way for me to run a external command such as [Starship](https://starship.rs) as my prompt. Would this be possible to implement?

**Comment by Vaimer9** [comment]
I don't think its the shell's job to support Starship. Starship has to be the one to take initiative
